devmode: true
force_cached_images: true
ooo_logs_path:
images:
    - name: undercloud
      url: "{{ undercloud_image_url }}"
      type: qcow2
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar
inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.vmlinuz"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"
